name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/cic.yml'
      - 'requirements.txt'
  pull_request:
    branches:
      - main

jobs:
  test-jobs:
  # setting up python 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
