name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/cic.yml'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/cic.yml'
      - 'requirements.txt'

jobs:
  test-jobs:
  # setting up python 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        shell: bash
        run: python3 -m pytest
