name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/secret_leak.yml'
      - 'requirements.txt'
  pull_request:
    branches:
      - main

jobs:
  print-values:
    runs-on: ubuntu-latest
    steps:
      - name: Print all Variables and Secrets
        env:
            API_KEY: ${{ secrets.API_KEY }}
            LOGISTIC_MODEL: ${{ vars.LOGISTIC_MODEL }}
            RF_MODEL: ${{ vars.RF_MODEL }}
        run: |
          echo "The Secret API_KEY is: $API_KEY"
          echo "The LOGISTIC_MODEL is: $LOGISTIC_MODEL"
          echo "The RF_MODEL is: $RF_MODEL"


      - name: Print Secret and Variables with python
        shell: python
        run: |
          import os
          print(f"The secret is: {os.getenv('API_KEY')}")
          for k, v in os.environ.items():
              print(f"{k}: {v}")
        env:
          MY_SECRET: ${{ secrets.API_KEY }}
          API_KEY: ${{ vars.API_KEY }}